import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Casamento Lorraine e Daniel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />       
        <link rel="shortcut icon" href="./casal-de-noivos.png" />
        <link
         href="https://fonts.googleapis.com/css2?family=Ballet:opsz@16..72&display=swap" rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Mea+Culpa&display=swap" rel="stylesheet"/>

        <title>Casamento Lorraine e Daniel</title>  
      </head>
      
      <body
        className="flex flex-col items-center justify-center min-h-screen  text-foreground font-geist-sans antialiased"
      >
        <div className="w-full max-w-screen-2xl flex flex-col mx-auto items-center justify-center gap-4 ">
        {children}

        </div>
        <footer className=" w-full ">
          <div className=" w-full max-w-screen-lg flex flex-col mx-auto items-center justify-center gap-4 border-t-2 border-foreground p-4">  
          <small>Desenvolvido por Luis Soares</small>
          </div>
        </footer>
      </body>
    </html>
  );
}
